export enum EventType {
  LOAD = "midi-load",
  LIST = "midi-list",
  NOTEON = "midi-note-on",
  NOTEOFF = "midi-note-off",
  POLY_AFTERTOUCH = "midi-poly-aftertouch",
  CONTROL_CHANGE = "midi-control-change",
  PROGRAM = "midi-program",
  CHANNEL_AFTERTOUCH = "midi-channel-aftertouch",
  PITCH = "midi-pitch",
  POSITION = "midi-position",
  MTC = "midi-mtc",
  SELECT = "midi-select",
  CLOCK = "midi-clock",
  START = "midi-start",
  CONTINUE = "midi-continue",
  STOP = "midi-stop",
  ACTIVE_SENSE = "midi-active-sense",
  RESET = "midi-reset",
  SYSEX = "midi-sysex",
  ERROR = "midi-error",
}
