name: Module MIDI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  module-midi:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Linux Deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev

      - name: Build
        run: |
          yarn
          yarn prebuild:x64

      - name: Linux x64 build and pack
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          yarn build:x64:linux
          cd build/linux-x64
          npx bestzip ../../midi-linux-x64.zip .

      - name: Windows x64 build and pack
        if: startsWith(matrix.os, 'windows')
        run: |
          yarn build:x64:win
          cd build/win-x64
          npx bestzip ../../midi-win-x64.zip .

      - name: Macos x64 build and pack
        if: startsWith(matrix.os, 'macos')
        run: |
          yarn build:x64:macos
          cd build/macos-x64
          npx bestzip ../../midi-macos-x64.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.zip