name: Module Midi

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Linux Deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev

      - name: Prepare dist
        run: mkdir ./dist

      - name: Copy metadata.json
        run: |
          cp ./metadata.json ./dist/metadata.json

      - name: Copy defaultConfig.json
        run: |
          cp ./config.json ./dist/config.json

      - name: Populate metadata.json __MODULE_REPO__
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "__MODULE_REPO__"
          replace: ${{ github.repository }}
          regex: false

      - name: Populate metadata.json __MODULE_VERSION__
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "__MODULE_VERSION__"
          replace: ${{ steps.get_version.outputs.version }}
          regex: false

      - name: Copy triggers
        run: |
          if [[ -d "./triggers" ]]
          then
            mkdir ./dist/triggers
            cp -a ./triggers/. ./dist/triggers
          fi

      - name: Copy shared
        run: |
          if [[ -d "./shared" ]]
          then
            mkdir ./dist/shared
            cp -a ./shared/. ./dist/shared
          fi

      - name: Build module
        run: |
          cd module
          yarn
          yarn build

      - name: Copy module
        run: |
          mkdir ./dist/module
          cp -a ./module/build/. ./dist/module

      - name: Pack Linux x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'ubuntu')
        run: |
          cd ./dist/
          npx bestzip ../${{ github.event.repository.name }}-linux-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Pack Win x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'windows')
        run: |
          cd ./dist/
          npx bestzip ../${{ github.event.repository.name }}-win-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Pack Macos x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'macos')
        run: |
          cd ./dist/
          npx bestzip ../${{ github.event.repository.name }}-macos-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.zip