name: Module MIDI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  module-midi:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Linux Deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev

      - name: Build
        run: |
          yarn
          yarn build

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Artefact Macos x64
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'macos')
        with:
          name: Module Midi MacOS x64
          path: ./dist/

      - name: Artefact Linux x64
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          name: Module Midi Linux x64
          path: ./dist/

      - name: Artefact Win x64
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v2
        with:
          name: Module Midi Windows x64
          path: ./dist/

      - name: Pack Linux x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'ubuntu')
        run: |
          cd ./dist/
          npx bestzip ../module-midi-linux-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Pack Win x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'windows')
        run: |
          cd ./dist/
          npx bestzip ../module-midi-win-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Pack Macos x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'macos')
        run: |
          cd ./dist/
          npx bestzip ../module-midi-macos-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.zip