name: Module MIDI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  module-midi:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Linux Deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev

      - name: Linux x64 build
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          yarn
          yarn prebuild:x64
          yarn build:x64:linux
          mkdir -p build/linux-x64/midi/build/Release/
          cp node_modules/midi/build/Release/midi.node build/linux-x64/midi/build/Release/midi.node
          cd build/linux-x64
          npx bestzip ../../midi-linux-x64.zip .

      - name: Windows x64 build
        if: startsWith(matrix.os, 'windows')
        run: |
          yarn
          yarn prebuild:x64
          yarn build:x64:win
          mkdir -p build/win-x64/midi/build/Release/
          copy node_modules/midi/build/Release/midi.node ./build/win-x64/midi/build/Release/midi.node
          cd build/win-x64
          npx bestzip ../../midi-win-x64.zip .

      - name: Macos x64 build
        if: startsWith(matrix.os, 'macos')
        run: |
          yarn
          yarn prebuild:x64
          yarn build:x64:macos
          mkdir -p build/macos-x64/midi/build/Release/
          cp node_modules/midi/build/Release/midi.node ./build/macos-x64/midi/build/Release/midi.node
          cd build/macos-x64
          npx bestzip ../../midi-macos-x64.zip .

      - name: Artefact Macos x64
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'macos')
        with:
          name: Midi MacOS x64
          path: ./build/macos-x64

      - name: Artefact Linux x64
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          name: Midi Linux x64
          path: ./build/linux-x64

      - name: Artefact Win x64
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v2
        with:
          name: Midi Windows x64
          path: ./build/win-x64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.zip